import"./assets/styles-JE8YjOlG.js";import{a as y,i as f}from"./assets/vendor-4yCzdkXl.js";const r={categoryBtn:document.querySelector(".categories__btn"),categories:document.querySelector(".categories"),products:document.querySelector(".products"),loadMoreBtn:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),themeBtn:document.querySelector(".theme-toggle-btn"),scrollTopBtn:document.querySelector(".scroll-top-btn"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalRenderProduct:document.querySelector(".modal-product"),productsItem:document.querySelector(".products__item")};function b(t){const e=t.map(s=>`<li class="categories__item">
    <button class="categories__btn" type="button">${s}</button>
        </li>`).join("");r.categories.innerHTML=e}function i(t,e=!1){const s=t.map(o=>`<li class="products__item" data-id="${o.id}">
        <img class="products__image" src="${o.thumbnail}" alt="${o.title}"/>
        <p class="products__title">${o.title}</p>
        <p class="products__brand"><span class="products__brand--bold">Brand: </span>${o.brand}</p>
        <p class="products__category">Category: ${o.category}</p>
    <p class="products__price">Price: $${o.price}</p>
        </li>`).join("");e?r.products.insertAdjacentHTML("beforeend",s):r.products.innerHTML=s}function $(t){const e=`<img class="modal-product__img" src="${t.thumbnail}" alt="${t.title}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t.title}</p>
        <ul class="modal-product__tags">${t.tags.map(s=>`<li>${s}</li>`).join("")}</ul>
        <p class="modal-product__description">${t.description}</p>
        <p class="modal-product__shipping-information">Shipping:${t.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy:${t.returnPolicy}</p>
        <p class="modal-product__price">Price: $${t.price}</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;r.modalRenderProduct.innerHTML=e}const l=y.create({baseURL:"https://dummyjson.com"});async function h(){return(await l.get("/products/category-list")).data}async function m(t=1,e=12){const s=(t-1)*e;return(await l.get("/products",{params:{limit:e,skip:s}})).data}async function g(t,e=1,s=12){const o=(e-1)*s;return(await l.get(`/products/category/${t}`,{params:{limit:s,skip:o}})).data}async function L(t){return(await l.get(`/products/${t}`)).data}async function _(t,e=1,s=12){const o=(e-1)*s;return(await l.get("/products/search/",{params:{q:t,limit:s,skip:o}})).data}let a=1;const c=12;let u="All",p="";function d(t){const e=a*c,s=t.total,o=t.products.length;e>=s||o<c?r.loadMoreBtn.classList.add("is-hidden"):r.loadMoreBtn.classList.remove("is-hidden")}async function v(){const t=await h();t.unshift("All"),b(t);const e=await m(a,c);i(e.products),d(e),r.categories.querySelector(".categories__btn").classList.add("categories__btn--active")}r.loadMoreBtn.addEventListener("click",async t=>{a+=1;let e;p?e=await _(p,a,c):u==="All"?e=await m(a,c):e=await g(u,a,c),i(e.products,!0),d(e)});v();r.categories.addEventListener("click",async t=>{const e=t.target.closest(".categories__btn");if(!e)return;const s=e.textContent;u=s;const o=r.categories.querySelector(".categories__btn--active");if(a=1,o&&o.classList.remove("categories__btn--active"),e.classList.add("categories__btn--active"),s==="All"){const n=await m(a,c);i(n.products),d(n)}else{const n=await g(s,a,c);i(n.products),d(n)}});r.searchForm.addEventListener("submit",async t=>{t.preventDefault();const s=new FormData(t.target).get("searchValue").trim();if(s===""){f.error({message:"Write pls somptng"});return}p=s,a=1,u="All";const o=await _(p,a,c);o.products.length===0?(r.products.innerHTML="",r.notFound.classList.add("is-visible")):(r.notFound.classList.remove("is-visible"),i(o.products)),d(o),r.searchForm.reset()});r.products.addEventListener("click",async t=>{const e=t.target.closest(".products__item");if(!e)return;const s=e.dataset.id,o=await L(s);$(o),r.modal.classList.add("modal--is-open")});
//# sourceMappingURL=index.js.map
