import"./assets/styles-JE8YjOlG.js";import{a as y,i as f}from"./assets/vendor-4yCzdkXl.js";const s={categoryBtn:document.querySelector(".categories__btn"),categories:document.querySelector(".categories"),products:document.querySelector(".products"),loadMoreBtn:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),themeBtn:document.querySelector(".theme-toggle-btn"),scrollTopBtn:document.querySelector(".scroll-top-btn"),notFound:document.querySelector(".not-found"),modal:document.querySelector(".modal"),modalRenderProduct:document.querySelector(".modal-product"),productsItem:document.querySelector(".products__item"),modalCloseBtn:document.querySelector(".modal__close-btn")};function b(t){const e=t.map(o=>`<li class="categories__item">
    <button class="categories__btn" type="button">${o}</button>
        </li>`).join("");s.categories.innerHTML=e}function i(t,e=!1){const o=t.map(a=>`<li class="products__item" data-id="${a.id}">
        <img class="products__image" src="${a.thumbnail}" alt="${a.title}"/>
        <p class="products__title">${a.title}</p>
        <p class="products__brand"><span class="products__brand--bold">Brand: </span>${a.brand}</p>
        <p class="products__category">Category: ${a.category}</p>
    <p class="products__price">Price: $${a.price}</p>
        </li>`).join("");e?s.products.insertAdjacentHTML("beforeend",o):s.products.innerHTML=o}function L(t){const e=`<img class="modal-product__img" src="${t.thumbnail}" alt="${t.title}" />
      <div class="modal-product__content">
        <p class="modal-product__title">${t.title}</p>
        <ul class="modal-product__tags">${t.tags.map(o=>`<li>${o}</li>`).join("")}</ul>
        <p class="modal-product__description">${t.description}</p>
        <p class="modal-product__shipping-information">Shipping:${t.shippingInformation}</p>
        <p class="modal-product__return-policy">Return Policy:${t.returnPolicy}</p>
        <p class="modal-product__price">Price: $${t.price}</p>
        <button class="modal-product__buy-btn" type="button">Buy</button>
      </div>`;s.modalRenderProduct.innerHTML=e}const l=y.create({baseURL:"https://dummyjson.com"});async function v(){return(await l.get("/products/category-list")).data}async function m(t=1,e=12){const o=(t-1)*e;return(await l.get("/products",{params:{limit:e,skip:o}})).data}async function g(t,e=1,o=12){const a=(e-1)*o;return(await l.get(`/products/category/${t}`,{params:{limit:o,skip:a}})).data}async function $(t){return(await l.get(`/products/${t}`)).data}async function _(t,e=1,o=12){const a=(e-1)*o;return(await l.get("/products/search/",{params:{q:t,limit:o,skip:a}})).data}let r=1;const c=12;let u="All",p="";function d(t){const e=r*c,o=t.total,a=t.products.length;e>=o||a<c?s.loadMoreBtn.classList.add("is-hidden"):s.loadMoreBtn.classList.remove("is-hidden")}async function h(){const t=await v();t.unshift("All"),b(t);const e=await m(r,c);i(e.products),d(e),s.categories.querySelector(".categories__btn").classList.add("categories__btn--active")}s.loadMoreBtn.addEventListener("click",async t=>{r+=1;let e;p?e=await _(p,r,c):u==="All"?e=await m(r,c):e=await g(u,r,c),i(e.products,!0),d(e)});h();s.categories.addEventListener("click",async t=>{const e=t.target.closest(".categories__btn");if(!e)return;const o=e.textContent;u=o;const a=s.categories.querySelector(".categories__btn--active");if(r=1,a&&a.classList.remove("categories__btn--active"),e.classList.add("categories__btn--active"),o==="All"){const n=await m(r,c);i(n.products),d(n)}else{const n=await g(o,r,c);i(n.products),d(n)}});s.searchForm.addEventListener("submit",async t=>{t.preventDefault();const o=new FormData(t.target).get("searchValue").trim();if(o===""){f.error({message:"Write pls somptng"});return}p=o,r=1,u="All";const a=await _(p,r,c);a.products.length===0?(s.products.innerHTML="",s.notFound.classList.add("is-visible")):(s.notFound.classList.remove("is-visible"),i(a.products)),d(a),s.searchForm.reset()});s.products.addEventListener("click",async t=>{const e=t.target.closest(".products__item");if(!e)return;const o=e.dataset.id,a=await $(o);L(a),s.modal.classList.add("modal--is-open")});s.modal.addEventListener("click",async t=>{t.target===s.modal&&s.modal.classList.remove("modal--is-open")});s.modalCloseBtn.addEventListener("click",t=>{s.modal.classList.remove("modal--is-open")});window.addEventListener("keyup",t=>{t.key==="Escape"&&s.modal.classList.contains("modal--is-open")&&s.modal.classList.remove("modal--is-open")});
//# sourceMappingURL=index.js.map
