import"./assets/styles-JE8YjOlG.js";import{a as _,i as f}from"./assets/vendor-4yCzdkXl.js";const a={categoryBtn:document.querySelector(".categories__btn"),categories:document.querySelector(".categories"),products:document.querySelector(".products"),loadMoreBtn:document.querySelector(".load-more-btn"),searchForm:document.querySelector(".search-form"),themeBtn:document.querySelector(".theme-toggle-btn"),scrollTopBtn:document.querySelector(".scroll-top-btn"),notFound:document.querySelector(".not-found")};function b(e){const t=e.map(s=>`<li class="categories__item">
    <button class="categories__btn" type="button">${s}</button>
        </li>`).join("");a.categories.innerHTML=t}function i(e,t=!1){const s=e.map(r=>`<li class="products__item" data-id="${r.id}">
        <img class="products__image" src="${r.thumbnail}" alt="${r.title}"/>
        <p class="products__title">${r.title}</p>
        <p class="products__brand"><span class="products__brand--bold">Brand: </span>${r.brand}</p>
        <p class="products__category">Category: ${r.category}</p>
    <p class="products__price">Price: $${r.price}</p>
        </li>`).join("");t?a.products.insertAdjacentHTML("beforeend",s):a.products.innerHTML=s}const p=_.create({baseURL:"https://dummyjson.com"});async function h(){return(await p.get("/products/category-list")).data}async function g(e=1,t=12){const s=(e-1)*t;return(await p.get("/products",{params:{limit:t,skip:s}})).data}async function m(e,t=1,s=12){const r=(t-1)*s;return(await p.get(`/products/category/${e}`,{params:{limit:s,skip:r}})).data}async function y(e,t=1,s=12){const r=(t-1)*s;return(await p.get("/products/search/",{params:{q:e,limit:s,skip:r}})).data}let o=1;const c=12;let d="All",l="";function u(e){const t=o*c,s=e.total,r=e.products.length;t>=s||r<c?a.loadMoreBtn.classList.add("is-hidden"):a.loadMoreBtn.classList.remove("is-hidden")}async function L(){const e=await h();e.unshift("All"),b(e);const t=await g(o,c);i(t.products),u(t),a.categories.querySelector(".categories__btn").classList.add("categories__btn--active")}a.loadMoreBtn.addEventListener("click",async e=>{o+=1;let t;l?t=await y(l,o,c):d==="All"?t=await g(o,c):t=await m(d,o,c),i(t.products,!0),u(t)});L();a.categories.addEventListener("click",async e=>{const t=e.target.closest(".categories__btn");if(!t)return;const s=t.textContent;d=s;const r=a.categories.querySelector(".categories__btn--active");if(o=1,r&&r.classList.remove("categories__btn--active"),t.classList.add("categories__btn--active"),s==="All"){const n=await g(o,c);i(n.products),u(n)}else{const n=await m(s,o,c);i(n.products),u(n)}});a.searchForm.addEventListener("submit",async e=>{e.preventDefault();const s=new FormData(e.target).get("searchValue").trim();if(s===""){f.error({message:"Write pls somptng"});return}l=s,o=1,d="All";const r=await y(l,o,c);r.products.length===0?(a.products.innerHTML="",a.notFound.classList.add("is-visible")):(a.notFound.classList.remove("is-visible"),i(r.products)),u(r),a.searchForm.reset()});
//# sourceMappingURL=index.js.map
